---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker
#
# tasks file for debian_security

# Manage required system packages [[[1
- name: Ensure required packages are in there desired state
  package:
    name: '{{ item }}'
    state: '{{ "present" if (deb_sec__deploy_state == "present")
                         else "absent" }}'
    install_recommends: False
  with_flattened:
    - '{{ deb_sec__required_packages }}'
