---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker
#
# tasks file for debian_security

# Manage required system packages [[[1
- name: Ensure required packages are in there desired state
  package:
    name: '{{ item }}'
    state: '{{ "present" if (deb_sec__deploy_state == "present")
                         else "absent" }}'
    install_recommends: False
  with_flattened:
    - '{{ deb_sec__required_packages }}'
# Debsecan [[[1
- name: Debsecan configuration
  template:
    src: 'etc/default/debsecan.j2'
    dest: '/etc/default/debsecan'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: (deb_sec__deploy_state == "present")
